const fs = require('fs');
const dest = 'c:/Users/Administrador/Documents/Sistema de gesti\u00f3n gastronomico/public/js/menu.js';

const L = [];
L.push('// GASTROMANAGER - Menu Publico (carta QR)');
L.push('');
L.push('function menuMoneda(v){');
L.push("  return new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:0}).format(v||0);");
L.push('}');
L.push('function menuEsc(s){');
L.push("  if(s===null||s===undefined)return '';");
L.push("  return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;').replace(/'/g,'&#039;');");
L.push('}');
L.push('');
L.push('const MenuPublico={');
L.push('  categorias:[],productos:[],catActiva:"todas",');
L.push('');
L.push('  async init(){');
L.push("    const fy=document.getElementById('footerYear');");
L.push('    if(fy)fy.textContent=new Date().getFullYear();');
L.push('    try{');
L.push("      const[data,cfg]=await Promise.all([fetch('/api/publico/menu').then(r=>{if(!r.ok)throw new Error(r.status);return r.json();}),fetch('/api/publico/info').then(r=>r.json()).catch(()=>null)]);");
L.push('      this.categorias=data.categorias||[];');
L.push('      this.productos=data.productos||[];');
L.push("      if(cfg&&cfg.nombre){const h=document.getElementById('menuRestNombre'),s=document.getElementById('menuRestSub'),fd=document.getElementById('footerDireccion'),ft=document.getElementById('footerTelefono');");
L.push("        if(h)h.textContent=cfg.nombre;if(s)s.textContent=cfg.descripcion||'';");
L.push("        if(fd&&cfg.descripcion)fd.textContent=cfg.descripcion.replace('Direcci\u00f3n: ','');");
L.push("        if(ft&&cfg.telefono){ft.textContent=cfg.telefono;ft.href='tel:'+cfg.telefono;}");
L.push('      }');
L.push('      this.paintCategorias();this.paintItems();');
L.push("    }catch(err){const el=document.getElementById('menuItems');");
L.push('      if(el)el.innerHTML=\'<div class="menu-empty"><i class="fas fa-exclamation-circle"></i><p>No se pudo cargar el men\u00fa. Intent\u00e1 de nuevo m\u00e1s tarde.</p></div>\';');
L.push("      console.error('[MenuPublico]',err);");
L.push('    }');
L.push('  },');
L.push('');
L.push('  catIcon(n){');
L.push("    n=(n||'').toLowerCase();");
L.push("    if(n.includes('entrada')||n.includes('entrante'))return 'fa-utensils';");
L.push("    if(n.includes('plato')||n.includes('principal')||n.includes('parrilla'))return 'fa-drumstick-bite';");
L.push("    if(n.includes('alcoh')||n.includes('vino')||n.includes('cerveza'))return 'fa-wine-glass';");
L.push("    if(n.includes('bebida')||n.includes('gaseosa')||n.includes('jugo'))return 'fa-glass-water';");
L.push("    if(n.includes('postre')||n.includes('dulce')||n.includes('torta')||n.includes('helado'))return 'fa-ice-cream';");
L.push("    if(n.includes('delivery')||n.includes('domicilio')||n.includes('llevar'))return 'fa-motorcycle';");
L.push("    if(n.includes('ensalada')||n.includes('verdura')||n.includes('saludable'))return 'fa-leaf';");
L.push("    if(n.includes('desayuno')||n.includes('cafe')||n.includes('caf\u00e9'))return 'fa-mug-hot';");
L.push("    if(n.includes('sandwich')||n.includes('burger')||n.includes('hambur'))return 'fa-burger';");
L.push("    if(n.includes('pizza')||n.includes('empanada'))return 'fa-pizza-slice';");
L.push("    return 'fa-tag';");
L.push('  },');

fs.writeFileSync(dest, L.join('\n'), 'utf8');
console.log('p1 ok bytes:', fs.statSync(dest).size);


const lines = [];
lines.push('');
lines.push('  itemCard(p) {');
lines.push('    const desc = p.descripcion ? `<div class="menu-item-desc">${menuEsc(p.descripcion)}</div>` : "";');
lines.push('    return `<article class="menu-item-card">');
lines.push('        <div class="menu-item-header">');
lines.push('          <div class="menu-item-info">');
lines.push('            <div class="menu-item-nombre">${menuEsc(p.nombre)}</div>');
lines.push('            ${desc}');
lines.push('          </div>');
lines.push('          <div class="menu-item-precio">${menuMoneda(p.precio_venta)}</div>');
lines.push('        </div>');
lines.push('      </article>`;');
lines.push('  },');
lines.push('');
lines.push('  sectionBlock(categoria, productos) {');
lines.push('    if (!productos.length) return "";');
lines.push('    const items = productos.map(p => this.itemCard(p)).join("");');
lines.push('    const icon  = this.catIcon(categoria.nombre);');
lines.push('    const title = menuEsc(categoria.nombre);');
lines.push('    return `<section class="menu-section reveal">');
lines.push('        <div class="menu-section-title"><i class="fas ${icon}"></i> ${title}</div>');
lines.push('        ${items}');
lines.push('      </section>`;');
lines.push('  },');
lines.push('');
lines.push('  visible(p) {');
lines.push('    return p.tracking_stock ? (p.stock_actual > 0 || p.es_plato === 1) : true;');
lines.push('  },');
lines.push('');
lines.push('  paintItems() {');
lines.push("    const el = document.getElementById('menuItems');");
lines.push('    if (!el) return;');
lines.push('    const visibles = this.productos.filter(p => this.visible(p));');
lines.push('    if (this.catActiva === "todas") {');
lines.push('      const html = this.categorias');
lines.push('        .map(cat => this.sectionBlock(cat, visibles.filter(p => p.categoria_id == cat.id)))');
lines.push('        .join("");');
lines.push('      el.innerHTML = html || \'<div class="menu-empty"><i class="fas fa-utensils"></i><p>No hay productos disponibles.</p></div>\';');
lines.push('    } else {');
lines.push('      const cat   = this.categorias.find(c => c.id == this.catActiva);');
lines.push('      const items = visibles.filter(p => p.categoria_id == this.catActiva);');
lines.push('      if (!cat) {');
lines.push('        el.innerHTML = \'<div class="menu-empty"><i class="fas fa-search"></i><p>Categor\u00eda no encontrada.</p></div>\';');
lines.push('      } else {');
lines.push('        el.innerHTML = this.sectionBlock(cat, items) || \'<div class="menu-empty"><i class="fas fa-box-open"></i><p>No hay productos en esta categor\u00eda.</p></div>\';');
lines.push('      }');
lines.push('    }');
lines.push('    this.setupReveal();');
lines.push('  },');
lines.push('');
lines.push('  setupReveal() {');
lines.push('    const items = document.querySelectorAll(".reveal:not(.visible)");');
lines.push('    if (!items.length) return;');
lines.push('    if ("IntersectionObserver" in window) {');
lines.push('      const obs = new IntersectionObserver((entries) => {');
lines.push('        entries.forEach(e => {');
lines.push('          if (e.isIntersecting) { e.target.classList.add("visible"); obs.unobserve(e.target); }');
lines.push('        });');
lines.push('      }, { threshold: 0.08, rootMargin: "0px 0px -30px 0px" });');
lines.push('      items.forEach(el => obs.observe(el));');
lines.push('    } else {');
lines.push('      items.forEach(el => el.classList.add("visible"));');
lines.push('    }');
lines.push('  }');
lines.push('};');
lines.push('');
lines.push("document.addEventListener('DOMContentLoaded', () => MenuPublico.init());");
lines.push('');

fs.appendFileSync(dest, lines.join('\n'), 'utf8');
console.log('parte3 ok - total bytes:', fs.statSync(dest).size);

lines.push("    const n = (nombre || '').toLowerCase();");
lines.push("    if (n.includes('entrada')  || n.includes('entrante'))                             return 'fa-utensils';");
lines.push("    if (n.includes('plato')    || n.includes('principal') || n.includes('parrilla'))  return 'fa-drumstick-bite';");
lines.push("    if (n.includes('alcoh')    || n.includes('vino')      || n.includes('cerveza'))   return 'fa-wine-glass';");
lines.push("    if (n.includes('bebida')   || n.includes('gaseosa')   || n.includes('jugo'))      return 'fa-glass-water';");
lines.push("    if (n.includes('postre')   || n.includes('dulce')     || n.includes('torta') || n.includes('helado')) return 'fa-ice-cream';");
lines.push("    if (n.includes('delivery') || n.includes('domicilio') || n.includes('llevar'))    return 'fa-motorcycle';");
lines.push("    if (n.includes('ensalada') || n.includes('verdura')   || n.includes('saludable')) return 'fa-leaf';");
lines.push("    if (n.includes('desayuno') || n.includes('cafe')      || n.includes('caf\u00e9'))      return 'fa-mug-hot';");
lines.push("    if (n.includes('sandwich') || n.includes('burger')    || n.includes('hambur'))    return 'fa-burger';");
lines.push("    if (n.includes('pizza')    || n.includes('empanada'))                             return 'fa-pizza-slice';");
lines.push("    return 'fa-tag';");
lines.push('  },');
lines.push('');
lines.push('  paintCategorias() {');
lines.push("    const desktop = document.getElementById('menuCategorias');");
lines.push("    const mobile  = document.getElementById('mobileCatScroll');");
lines.push('    const btnHTML = (id, label, icon) => {');
lines.push('      const active = this.catActiva == id ? "active" : "";');
lines.push('      return `<button class="menu-cat-btn ${active}" data-id="${id}"><i class="fas ${icon}"></i> ${menuEsc(label)}</button>`;');
lines.push('    };');
lines.push('    const allHTML = [');
lines.push("      btnHTML('todas', 'Todas', 'fa-border-all'),");
lines.push('      ...this.categorias.map(c => btnHTML(c.id, c.nombre, this.catIcon(c.nombre)))');
lines.push("    ].join('');");
lines.push('    const bindClicks = (container, isMobile) => {');
lines.push("      container.querySelectorAll('[data-id]').forEach(b => {");
lines.push("        b.addEventListener('click', () => {");
lines.push("          this.catActiva = b.getAttribute('data-id');");
lines.push('          this.paintCategorias(); this.paintItems();');
lines.push('          if (isMobile) {');
lines.push("            const mc = document.getElementById('menuContainer');");
lines.push("            if (mc) mc.scrollIntoView({ behavior: 'smooth' });");
lines.push('          }');
lines.push('        });');
lines.push('      });');
lines.push('    };');
lines.push('    if (desktop) {');
lines.push('      desktop.innerHTML = allHTML || \'<button class="menu-cat-btn active">Men\u00fa</button>\';');
lines.push('      bindClicks(desktop, false);');
lines.push('    }');
lines.push('    if (mobile) {');
lines.push("      mobile.innerHTML = allHTML.replace(/menu-cat-btn/g, 'mobile-cat-btn');");
lines.push('      bindClicks(mobile, true);');
lines.push('    }');
lines.push('  },');

fs.appendFileSync(dest, lines.join('\n'), 'utf8');
console.log('parte2 ok');
