'use strict';
// build-pj-2.js — itemCard + paintItems + carrito ops
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'js', 'pedido.js');
const L = [];
L.push('');
L.push('  itemCard(p){');
L.push('    const q=(this.carrito.find(i=>i.producto_id===p.id)||{cantidad:0}).cantidad;');
L.push('    const qc=q===0');
L.push('      ?`<button class="btn-agregar" onclick="PedidoOnline.agregar(${p.id})" aria-label="Agregar"><i class="fas fa-plus"></i> Agregar</button>`');
L.push('      :`<button class="btn-qty btn-qty-minus" onclick="PedidoOnline.quitar(${p.id})" aria-label="Quitar">&#8722;</button><span class="qty-num">${q}</span><button class="btn-qty btn-qty-plus" onclick="PedidoOnline.agregar(${p.id})" aria-label="Sumar">+</button>`;');
L.push('    return `<div class="menu-item-card pedido-item-card" data-id="${p.id}">');
L.push('  <div class="menu-item-info">');
L.push('    <div class="menu-item-nombre">${pdE(p.nombre)}</div>');
L.push('    ${p.descripcion?`<div class="menu-item-desc">${pdE(p.descripcion)}</div>`:""}');
L.push('    <div class="menu-item-precio">${pdM(p.precio_venta)}</div>');
L.push('  </div>');
L.push('  <div class="item-qty-ctrl">${qc}</div>');
L.push('</div>`;');
L.push('  },');
L.push('');
L.push('  paintItems(){');
L.push('    const el=document.getElementById("menuItems");');
L.push('    const vis=this.productos.filter(p=>this.visible(p));');
L.push('    const sec=(cat,prods)=>{');
L.push('      if(!prods.length)return"";');
L.push('      return`<div class="menu-section"><div class="menu-section-title"><i class="fas ${this.catIcon(cat.nombre)}"></i> ${pdE(cat.nombre)}</div>${prods.map(p=>this.itemCard(p)).join("")}</div>`;');
L.push('    };');
L.push('    if(this.catActiva==="todas"){');
L.push('      el.innerHTML=this.categorias.map(c=>sec(c,vis.filter(p=>p.categoria_id==c.id))).join("")||\'<div class="menu-empty">No hay productos.</div>\';');
L.push('    }else{');
L.push('      const cat=this.categorias.find(c=>c.id==this.catActiva);');
L.push('      const items=vis.filter(p=>p.categoria_id==this.catActiva);');
L.push('      el.innerHTML=cat?sec(cat,items)||\'<div class="menu-empty">Sin productos en esta categoria.</div>\':\'<div class="menu-empty">Categoria no encontrada.</div>\';');
L.push('    }');
L.push('  },');
L.push('');
L.push('  agregar(id){');
L.push('    const prod=this.productos.find(p=>p.id===id);if(!prod)return;');
L.push('    const item=this.carrito.find(i=>i.producto_id===id);');
L.push('    if(item)item.cantidad++;');
L.push('    else this.carrito.push({producto_id:id,nombre:prod.nombre,precio:prod.precio_venta,cantidad:1,notas:""});');
L.push('    this.paintItems();this.paintCarrito();');
L.push('  },');
L.push('');
L.push('  quitar(id){');
L.push('    const idx=this.carrito.findIndex(i=>i.producto_id===id);if(idx===-1)return;');
L.push('    this.carrito[idx].cantidad--;');
L.push('    if(this.carrito[idx].cantidad<=0)this.carrito.splice(idx,1);');
L.push('    this.paintItems();this.paintCarrito();');
L.push('  },');
L.push('');
L.push('  eliminar(id){');
L.push('    this.carrito=this.carrito.filter(i=>i.producto_id!==id);');
L.push('    this.paintItems();this.paintCarrito();');
L.push('  },');
L.push('');
L.push('  _carritoHTML(){');
L.push('    if(!this.carrito.length)return\'<div class="carrito-vacio"><i class="fas fa-shopping-bag"></i><p>Todavia no agregaste nada</p></div>\';');
L.push('    return this.carrito.map(i=>`<div class="carrito-item">');
L.push('  <div class="carrito-item-info"><span class="carrito-item-nombre">${pdE(i.nombre)}</span><span class="carrito-item-precio">${pdM(i.precio)}</span></div>');
L.push('  <div class="carrito-item-qty">');
L.push('    <button class="btn-qty btn-qty-minus" onclick="PedidoOnline.quitar(${i.producto_id})" aria-label="Quitar">&#8722;</button>');
L.push('    <span>${i.cantidad}</span>');
L.push('    <button class="btn-qty btn-qty-plus" onclick="PedidoOnline.agregar(${i.producto_id})" aria-label="Sumar">+</button>');
L.push('    <button class="btn-qty btn-qty-remove" onclick="PedidoOnline.eliminar(${i.producto_id})" aria-label="Eliminar"><i class="fas fa-trash-alt"></i></button>');
L.push('  </div>');
L.push('  <div class="carrito-item-sub">${pdM(i.precio*i.cantidad)}</div>');
L.push('</div>`).join("");');
L.push('  },');
L.push('');
L.push('  paintCarrito(){');
L.push('    const total=this.carrito.reduce((s,i)=>s+i.precio*i.cantidad,0);');
L.push('    const count=this.carrito.reduce((s,i)=>s+i.cantidad,0);');
L.push('    const html=this._carritoHTML();');
L.push('    const has=this.carrito.length>0;');
L.push('    const set=(id,val,prop)=>{const e=document.getElementById(id);if(e){if(prop==="html")e.innerHTML=val;else if(prop==="display")e.style.display=val;else if(prop==="text")e.textContent=val;}};');
L.push('    set("carritoItems",html,"html");set("carritoTotalRow",has?"":"none","display");set("carritoTotal",pdM(total),"text");');
L.push('    set("btnConfirmar",has?"":"none","display");set("carritoCount",count+(count===1?" item":" items"),"text");');
L.push('    set("carritoItemsMobile",html,"html");set("carritoTotalRowMobile",has?"":"none","display");set("carritoTotalMobile",pdM(total),"text");');
L.push('    set("btnConfirmarMobile",has?"":"none","display");');
L.push('    set("carritoFlotante",has?"":"none","display");set("carritoFlotanteCount",String(count),"text");');
L.push('  },');
fs.appendFileSync(out, L.join('\r\n'), 'utf8');
console.log('OK pedido.js parte-2');
