'use strict';
// build-pj-4.js — confirmacion + cierre del objeto PedidoOnline
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'js', 'pedido.js');
const L = [];
L.push('  _confirmar(data,nombre){');
L.push('    document.getElementById("formModal").style.display="none";');
L.push('    document.body.style.overflow="";');
L.push('    const msg=document.getElementById("confirmacionMsg");');
L.push('    const num=document.getElementById("confirmacionNumero");');
L.push('    if(msg)msg.textContent="Gracias "+nombre+"! Recibimos tu pedido y en breve te contactamos.";');
L.push('    if(num)num.innerHTML="Numero de pedido: <strong>"+pdE(data.numero_pedido)+"</strong>";');
L.push('    document.getElementById("confirmacionScreen").style.display="";');
L.push('    ["menuItems","menuCategorias"].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display="none";});');
L.push('    const sb=document.getElementById("carritoSidebar");if(sb)sb.style.display="none";');
L.push('    const fl=document.getElementById("carritoFlotante");if(fl)fl.style.display="none";');
L.push('    const nav=document.getElementById("mobileCatNav");if(nav)nav.style.display="none";');
L.push('  },');
L.push('  nuevoPedido(){');
L.push('    this.carrito=[];');
L.push('    document.getElementById("confirmacionScreen").style.display="none";');
L.push('    ["menuItems","menuCategorias"].forEach(id=>{const e=document.getElementById(id);if(e)e.style.display="";});');
L.push('    const sb=document.getElementById("carritoSidebar");if(sb)sb.style.display="";');
L.push('    const nav=document.getElementById("mobileCatNav");if(nav)nav.style.display="";');
L.push('    const form=document.getElementById("pedidoForm");if(form)form.reset();');
L.push('    const gd=document.getElementById("grupoDireccion");if(gd)gd.style.display="none";');
L.push('    this.paintItems();this.paintCarrito();');
L.push('  },');
L.push('  _initEvents(){');
L.push('    ["carritoMobileModal","formModal"].forEach(id=>{');
L.push('      const el=document.getElementById(id);');
L.push('      if(el)el.addEventListener("click",e=>{');
L.push('        if(e.target===el){');
L.push('          if(id==="carritoMobileModal")this.toggleCarritoMobile();');
L.push('          else this.cerrarFormulario();');
L.push('        }');
L.push('      });');
L.push('    });');
L.push('    document.addEventListener("keydown",e=>{');
L.push('      if(e.key!=="Escape")return;');
L.push('      this.cerrarFormulario();');
L.push('      const mm=document.getElementById("carritoMobileModal");');
L.push('      if(mm&&mm.style.display!=="none")this.toggleCarritoMobile();');
L.push('    });');
L.push('  }');
L.push('};');
L.push('document.addEventListener("DOMContentLoaded",()=>PedidoOnline.init());');
fs.appendFileSync(out, '\r\n' + L.join('\r\n'), 'utf8');
console.log('OK pedido.js parte-4 (completo)');
