'use strict';
// build-css-1.js — primera mitad de pedido.css
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'css', 'pedido.css');
if (fs.existsSync(out)) { console.log('SKIP pedido.css'); process.exit(0); }
const L = [];
const W = s => L.push(s);
W('/* GASTROMANAGER - Pedido Online Styles */');
W('');
W('.origen-badge-hero {');
W('  display:inline-flex;align-items:center;gap:8px;');
W('  padding:6px 16px;border-radius:20px;font-size:.85rem;');
W('  font-weight:600;margin-top:10px;');
W('}');
W('.badge-wa  { background:#25D366; color:#fff; }');
W('.badge-ig  { background:linear-gradient(45deg,#f09433,#e6683c,#dc2743,#cc2366,#bc1888); color:#fff; }');
W('.badge-web { background:rgba(255,255,255,.2); color:#fff; border:1px solid rgba(255,255,255,.4); }');
W('');
W('.pedido-layout {');
W('  display:flex;gap:24px;max-width:1200px;');
W('  margin:0 auto;padding:24px 16px;align-items:flex-start;');
W('}');
W('.pedido-carta { flex:1; min-width:0; }');
W('');
W('.pedido-carrito-sidebar {');
W('  width:320px;flex-shrink:0;position:sticky;top:80px;');
W('  background:#fff;border-radius:16px;padding:20px;');
W('  box-shadow:0 4px 24px rgba(0,0,0,.10);');
W('}');
W('.carrito-header {');
W('  display:flex;justify-content:space-between;align-items:center;');
W('  margin-bottom:16px;padding-bottom:12px;border-bottom:2px solid #f3f4f6;');
W('}');
W('.carrito-header h3 { margin:0;font-size:1.05rem;font-weight:700;color:#1f2937; }');
W('.carrito-count { font-size:.8rem;color:#6b7280;background:#f3f4f6;padding:3px 10px;border-radius:12px; }');
W('');
W('.carrito-items { max-height:340px;overflow-y:auto; }');
W('.carrito-vacio { text-align:center;padding:32px 16px;color:#9ca3af; }');
W('.carrito-vacio i { font-size:2rem;display:block;margin-bottom:8px; }');
W('.carrito-item {');
W('  display:grid;grid-template-columns:1fr auto auto;');
W('  gap:8px;align-items:center;padding:10px 0;border-bottom:1px solid #f3f4f6;');
W('}');
W('.carrito-item:last-child { border-bottom:none; }');
W('.carrito-item-info { min-width:0; }');
W('.carrito-item-nombre { display:block;font-size:.9rem;font-weight:600;');
W('  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;color:#1f2937; }');
W('.carrito-item-precio { font-size:.8rem;color:#6b7280; }');
W('.carrito-item-qty { display:flex;align-items:center;gap:6px; }');
W('.carrito-item-sub { font-size:.9rem;font-weight:700;color:#f97316;text-align:right; }');
W('');
W('.carrito-total-row {');
W('  display:flex;justify-content:space-between;align-items:center;');
W('  padding:14px 0 10px;border-top:2px solid #f3f4f6;');
W('  margin-top:8px;font-weight:700;font-size:1rem;');
W('}');
W('.carrito-total-row strong { color:#f97316;font-size:1.15rem; }');
W('.btn-block { width:100%;margin-top:10px; }');
W('');
W('.btn-agregar {');
W('  background:#f97316;color:#fff;border:none;cursor:pointer;');
W('  padding:7px 14px;border-radius:8px;font-size:.85rem;font-weight:600;');
W('  display:flex;align-items:center;gap:6px;transition:background .2s;');
W('}');
W('.btn-agregar:hover { background:#ea6c0a; }');
W('.btn-qty {');
W('  width:30px;height:30px;border-radius:8px;border:none;cursor:pointer;');
W('  font-size:1rem;font-weight:700;transition:all .15s;');
W('  display:flex;align-items:center;justify-content:center;');
W('}');
W('.btn-qty-minus,.btn-qty-plus { background:#f3f4f6;color:#374151; }');
W('.btn-qty-minus:hover,.btn-qty-plus:hover { background:#e5e7eb; }');
W('.btn-qty-remove { background:#fee2e2;color:#dc2626;font-size:.8rem; }');
W('.btn-qty-remove:hover { background:#fca5a5; }');
W('.qty-num { min-width:24px;text-align:center;font-weight:700;font-size:.95rem; }');
W('');
W('.carrito-flotante {');
W('  position:fixed;bottom:24px;right:20px;z-index:900;');
W('  background:#f97316;color:#fff;border:none;cursor:pointer;');
W('  width:60px;height:60px;border-radius:50%;');
W('  box-shadow:0 4px 20px rgba(249,115,22,.5);');
W('  display:flex;align-items:center;justify-content:center;');
W('  font-size:1.4rem;transition:transform .2s;');
W('}');
W('.carrito-flotante:hover { transform:scale(1.08); }');
W('.carrito-flotante-count {');
W('  position:absolute;top:-4px;right:-4px;');
W('  background:#dc2626;color:#fff;border-radius:50%;');
W('  width:22px;height:22px;font-size:.72rem;font-weight:700;');
W('  display:flex;align-items:center;justify-content:center;');
W('}');
fs.writeFileSync(out, L.join('\r\n'), 'utf8');
console.log('OK pedido.css parte-1');
