'use strict';
// build-pedido-js-1.js — cabecera + init + categorias
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'js', 'pedido.js');
if (fs.existsSync(out)) { console.log('SKIP pedido.js'); process.exit(0); }
const L = [];
L.push('// GASTROMANAGER - Pedido Online (WhatsApp / Instagram)');
L.push('function pdM(v){return new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",minimumFractionDigits:0}).format(v||0);}');
L.push('function pdE(s){if(s==null)return"";return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");}');
L.push('');
L.push('const PedidoOnline={');
L.push('  categorias:[],productos:[],carrito:[],catActiva:"todas",origen:"web",config:{},');
L.push('');
L.push('  async init(){');
L.push('    const p=new URLSearchParams(location.search);');
L.push('    const o=p.get("origen")||"web";');
L.push('    this.origen=["whatsapp","instagram","web"].includes(o)?o:"web";');
L.push('    this._badge();');
L.push('    try{');
L.push('      const[m,info]=await Promise.all([');
L.push('        fetch("/api/publico/menu").then(r=>r.json()),');
L.push('        fetch("/api/publico/info").then(r=>r.json()).catch(()=>({}))');
L.push('      ]);');
L.push('      this.categorias=m.categorias||[];');
L.push('      this.productos=m.productos||[];');
L.push('      this.config=info;');
L.push('      if(info.nombre){document.getElementById("negocioNombre").textContent=info.nombre;document.title="Pedido | "+info.nombre;}');
L.push('      if(info.descripcion)document.getElementById("negocioSub").textContent=info.descripcion;');
L.push('      if(info.telefono){');
L.push('        const wa=document.getElementById("confirmacionWA");');
L.push('        if(wa){wa.href="https://wa.me/"+info.telefono.replace(/\\D/g,"");wa.style.display="";}');
L.push('      }');
L.push('      this.paintCats();this.paintItems();this._initEvents();');
L.push('    }catch(err){');
L.push('      document.getElementById("menuItems").innerHTML=\'<div class="menu-empty"><i class="fas fa-exclamation-triangle"></i><p>No se pudo cargar el menu.</p></div>\';');
L.push('    }');
L.push('  },');
L.push('');
L.push('  _badge(){');
L.push('    const b=document.getElementById("origenBadge");if(!b)return;');
L.push('    const m={whatsapp:{icon:"fab fa-whatsapp",label:"Pedido por WhatsApp",cls:"badge-wa"},instagram:{icon:"fab fa-instagram",label:"Pedido por Instagram",cls:"badge-ig"},web:{icon:"fas fa-globe",label:"Pedido Online",cls:"badge-web"}};');
L.push('    const i=m[this.origen]||m.web;');
L.push('    b.innerHTML=`<i class="${i.icon}"></i> ${i.label}`;');
L.push('    b.className="origen-badge-hero "+i.cls;b.style.display="";');
L.push('  },');
L.push('');
L.push('  catIcon(n){');
L.push('    n=(n||"").toLowerCase();');
L.push('    if(n.includes("entrada"))return"fa-utensils";');
L.push('    if(n.includes("plato")||n.includes("principal"))return"fa-drumstick-bite";');
L.push('    if(n.includes("bebida")||n.includes("gaseosa"))return"fa-glass-martini-alt";');
L.push('    if(n.includes("postre")||n.includes("helado"))return"fa-ice-cream";');
L.push('    if(n.includes("cafe"))return"fa-mug-hot";');
L.push('    return"fa-tag";');
L.push('  },');
L.push('');
L.push('  paintCats(){');
L.push('    const mk=(id,lbl)=>`<button class="menu-cat-btn ${this.catActiva==id?"active":""}" onclick="PedidoOnline.setCat(${JSON.stringify(id)})">${pdE(lbl)}</button>`;');
L.push('    const h=[mk("todas","Todas"),...this.categorias.map(c=>mk(c.id,c.nombre))].join("");');
L.push('    ["menuCategorias","mobileCatScroll"].forEach(id=>{const el=document.getElementById(id);if(el)el.innerHTML=h;});');
L.push('  },');
L.push('');
L.push('  setCat(id){this.catActiva=id;this.paintCats();this.paintItems();},');
L.push('  visible(p){return p.tracking_stock?(p.stock_actual>0||p.es_plato===1):true;},');
fs.writeFileSync(out, L.join('\r\n'), 'utf8');
console.log('OK pedido.js parte-1');
