'use strict';
// build-pj-3.js — modal, form, envio
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'js', 'pedido.js');
const L = [];
L.push('');
L.push('  toggleCarritoMobile(){');
L.push('    const m=document.getElementById("carritoMobileModal");if(!m)return;');
L.push('    const open=m.style.display!=="none";');
L.push('    m.style.display=open?"none":"";');
L.push('    document.body.style.overflow=open?"":"hidden";');
L.push('  },');
L.push('  abrirFormulario(){');
L.push('    const mm=document.getElementById("carritoMobileModal");');
L.push('    if(mm)mm.style.display="none";');
L.push('    this._paintResumen();');
L.push('    const fm=document.getElementById("formModal");');
L.push('    if(fm){fm.style.display="";document.body.style.overflow="hidden";}');
L.push('  },');
L.push('  cerrarFormulario(){');
L.push('    const fm=document.getElementById("formModal");');
L.push('    if(fm)fm.style.display="none";');
L.push('    document.body.style.overflow="";');
L.push('  },');
L.push('  onTipoChange(v){');
L.push('    const gd=document.getElementById("grupoDireccion");if(!gd)return;');
L.push('    gd.style.display=v==="delivery"?"":"none";');
L.push('    const dir=document.getElementById("clienteDireccion");');
L.push('    if(dir)dir.required=v==="delivery";');
L.push('  },');
L.push('  _paintResumen(){');
L.push('    const el=document.getElementById("formResumen");if(!el)return;');
L.push('    const total=this.carrito.reduce((s,i)=>s+i.precio*i.cantidad,0);');
L.push('    el.innerHTML=\'<div class="resumen-titulo">Resumen del pedido</div>\'');
L.push('      +this.carrito.map(i=>`<div class="resumen-row"><span>${pdE(i.nombre)} x${i.cantidad}</span><strong>${pdM(i.precio*i.cantidad)}</strong></div>`).join("")');
L.push('      +`<div class="resumen-total"><span>Total estimado</span><strong>${pdM(total)}</strong></div>`;');
L.push('  },');
L.push('  async enviarPedido(e){');
L.push('    e.preventDefault();');
L.push('    const nombre=document.getElementById("clienteNombre").value.trim();');
L.push('    const tel=document.getElementById("clienteTelefono").value.trim();');
L.push('    const tipo=(document.querySelector(\'input[name="tipoPedido"]:checked\')||{value:"takeaway"}).value;');
L.push('    const dir=document.getElementById("clienteDireccion").value.trim();');
L.push('    const notas=document.getElementById("clienteNotas").value.trim();');
L.push('    if(!nombre||!tel){alert("Completa nombre y telefono.");return;}');
L.push('    if(tipo==="delivery"&&!dir){alert("Completa la direccion de entrega.");return;}');
L.push('    if(!this.carrito.length){alert("Agrega al menos un producto.");return;}');
L.push('    const btn=document.getElementById("btnEnviar");');
L.push('    btn.disabled=true;');
L.push('    btn.innerHTML=\'<i class="fas fa-spinner fa-spin"></i> Enviando...\';');
L.push('    try{');
L.push('      const r=await fetch("/api/publico/pedido",{');
L.push('        method:"POST",headers:{"Content-Type":"application/json"},');
L.push('        body:JSON.stringify({cliente:nombre,telefono:tel,tipo,direccion:dir,notas,origen:this.origen,');
L.push('          items:this.carrito.map(i=>({producto_id:i.producto_id,nombre:i.nombre,cantidad:i.cantidad,notas:i.notas||""}))})');
L.push('      });');
L.push('      const data=await r.json();');
L.push('      if(!r.ok)throw new Error(data.error||"Error al enviar");');
L.push('      this._confirmar(data,nombre);');
L.push('    }catch(err){');
L.push('      alert("Error: "+err.message);');
L.push('      btn.disabled=false;');
L.push('      btn.innerHTML=\'<i class="fas fa-paper-plane"></i> Enviar pedido\';');
L.push('    }');
L.push('  },');
fs.appendFileSync(out, L.join('\r\n'), 'utf8');
console.log('OK pedido.js parte-3');
