'use strict';
// build-css-2.js — segunda mitad de pedido.css
const fs = require('fs'), pt = require('path');
const out = pt.join(__dirname, '..', 'public', 'css', 'pedido.css');
const L = [];
const W = s => L.push(s);
W('');
W('.carrito-mobile-overlay {');
W('  position:fixed;inset:0;z-index:1000;');
W('  background:rgba(0,0,0,.5);display:flex;');
W('  align-items:flex-end;animation:fadeIn .2s;');
W('}');
W('.carrito-mobile-sheet {');
W('  background:#fff;width:100%;border-radius:20px 20px 0 0;');
W('  padding:16px 20px 32px;max-height:85vh;overflow-y:auto;');
W('  animation:slideUp .25s ease-out;');
W('}');
W('.carrito-mobile-handle {');
W('  width:40px;height:4px;background:#d1d5db;');
W('  border-radius:2px;margin:0 auto 16px;');
W('}');
W('.btn-cerrar {');
W('  background:none;border:none;font-size:1.6rem;cursor:pointer;');
W('  color:#6b7280;line-height:1;padding:0 4px;');
W('}');
W('.btn-cerrar:hover { color:#1f2937; }');
W('');
W('.pedido-form-overlay {');
W('  position:fixed;inset:0;z-index:1100;');
W('  background:rgba(0,0,0,.6);');
W('  display:flex;align-items:center;justify-content:center;');
W('  padding:16px;animation:fadeIn .2s;');
W('}');
W('.pedido-form-modal {');
W('  background:#fff;border-radius:20px;width:100%;');
W('  max-width:480px;max-height:90vh;overflow-y:auto;');
W('  animation:scaleIn .2s ease-out;');
W('}');
W('.pedido-form-header {');
W('  display:flex;justify-content:space-between;align-items:center;');
W('  padding:20px 24px 0;');
W('}');
W('.pedido-form-header h3 { margin:0;font-size:1.1rem;font-weight:700; }');
W('.pedido-form-modal form { padding:20px 24px 28px; }');
W('.form-group { margin-bottom:16px; }');
W('.form-group label { display:block;font-weight:600;font-size:.9rem;margin-bottom:6px;color:#374151; }');
W('.form-group input,.form-group textarea {');
W('  width:100%;padding:10px 14px;border-radius:10px;');
W('  border:1.5px solid #d1d5db;font-size:.95rem;');
W('  transition:border-color .15s;box-sizing:border-box;');
W('}');
W('.form-group input:focus,.form-group textarea:focus {');
W('  outline:none;border-color:#f97316;');
W('  box-shadow:0 0 0 3px rgba(249,115,22,.15);');
W('}');
W('');
W('.tipo-opciones { display:flex;gap:12px;flex-wrap:wrap; }');
W('.tipo-opcion {');
W('  flex:1;min-width:120px;display:flex;align-items:center;gap:8px;');
W('  padding:12px 16px;border-radius:10px;border:2px solid #e5e7eb;');
W('  cursor:pointer;transition:all .15s;font-size:.9rem;');
W('}');
W('.tipo-opcion:has(input:checked) {');
W('  border-color:#f97316;background:#fff7ed;color:#c2410c;font-weight:600;');
W('}');
W('.tipo-opcion input { display:none; }');
W('');
W('.form-resumen {');
W('  background:#f9fafb;border-radius:12px;padding:14px 16px;');
W('  margin:16px 0;border:1px solid #e5e7eb;');
W('}');
W('.resumen-titulo { font-weight:700;font-size:.9rem;margin-bottom:8px;color:#374151; }');
W('.resumen-row { display:flex;justify-content:space-between;font-size:.88rem;padding:3px 0;color:#6b7280; }');
W('.resumen-total {');
W('  display:flex;justify-content:space-between;font-size:.95rem;font-weight:700;');
W('  padding-top:8px;margin-top:8px;border-top:1px solid #e5e7eb;color:#1f2937;');
W('}');
W('.resumen-total strong { color:#f97316; }');
W('.form-actions { display:flex;gap:10px;justify-content:flex-end;margin-top:20px; }');
W('');
W('.confirmacion-screen {');
W('  position:fixed;inset:0;z-index:2000;');
W('  background:linear-gradient(135deg,#fff7ed 0%,#fed7aa 100%);');
W('  display:flex;align-items:center;justify-content:center;padding:24px;');
W('}');
W('.confirmacion-card {');
W('  background:#fff;border-radius:24px;padding:40px 32px;');
W('  text-align:center;max-width:420px;width:100%;');
W('  box-shadow:0 8px 40px rgba(0,0,0,.12);');
W('}');
W('.confirmacion-icon { font-size:3.5rem;color:#22c55e;margin-bottom:16px; }');
W('.confirmacion-card h2 { margin:0 0 10px;color:#1f2937;font-size:1.5rem; }');
W('.confirmacion-card p { color:#6b7280;margin-bottom:16px; }');
W('.confirmacion-numero {');
W('  background:#f3f4f6;border-radius:10px;padding:10px 20px;');
W('  font-size:.95rem;color:#374151;display:inline-block;');
W('}');
W('');
W('.pedido-item-card {');
W('  display:flex;justify-content:space-between;align-items:center;');
W('  background:#fff;border-radius:14px;padding:14px 16px;');
W('  margin-bottom:10px;box-shadow:0 2px 8px rgba(0,0,0,.06);');
W('  transition:box-shadow .15s;');
W('}');
W('.pedido-item-card:hover { box-shadow:0 4px 16px rgba(0,0,0,.10); }');
W('.item-qty-ctrl { flex-shrink:0;margin-left:12px; }');
W('');
W('.btn-whatsapp {');
W('  background:#25D366;color:#fff;text-decoration:none;');
W('  display:inline-flex;align-items:center;gap:8px;');
W('  padding:10px 20px;border-radius:10px;font-weight:600;');
W('  font-size:.95rem;transition:background .2s;');
W('}');
W('.btn-whatsapp:hover { background:#1ebe57;color:#fff; }');
W('');
W('/* ---- Origen badge en tabla de pedidos (panel admin) ---- */');
W('.origen-badge { display:inline-flex;align-items:center;gap:5px;');
W('  font-size:.75rem;font-weight:600;padding:3px 8px;border-radius:8px; }');
W('.origen-badge.wa  { background:#d1fae5;color:#065f46; }');
W('.origen-badge.ig  { background:#fce7f3;color:#9d174d; }');
W('.origen-badge.web { background:#e0e7ff;color:#3730a3; }');
W('');
W('@keyframes fadeIn  { from{opacity:0} to{opacity:1} }');
W('@keyframes slideUp { from{transform:translateY(60px);opacity:0} to{transform:translateY(0);opacity:1} }');
W('@keyframes scaleIn { from{transform:scale(.95);opacity:0} to{transform:scale(1);opacity:1} }');
W('');
W('@media(max-width:768px) {');
W('  .pedido-layout { flex-direction:column;padding:12px; }');
W('  .pedido-carrito-sidebar { display:none; }');
W('}');
W('@media(min-width:769px) {');
W('  .carrito-flotante { display:none !important; }');
W('}');
fs.appendFileSync(out, '\r\n' + L.join('\r\n'), 'utf8');
console.log('OK pedido.css parte-2 (completo)');
