'use strict';
// ps3: crea public/pedido.html en partes
const fs = require('fs'), path = require('path');
const P  = path.join(__dirname, '..', 'public', 'pedido.html');
if (fs.existsSync(P)) { console.log('SKIP pedido.html'); process.exit(0); }

const head = [
'<!DOCTYPE html>',
'<html lang="es">',
'<head>',
'  <meta charset="UTF-8">',
'  <meta name="viewport" content="width=device-width, initial-scale=1.0">',
'  <meta name="theme-color" content="#f97316">',
'  <title>Pedido Online</title>',
'  <link rel="icon" href="favicon.svg" type="image/svg+xml">',
'  <link rel="stylesheet" href="css/styles.css">',
'  <link rel="stylesheet" href="css/menu.css">',
'  <link rel="stylesheet" href="css/pedido.css">',
'  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">',
'</head>',
'<body class="menu-body">',
'  <header class="menu-hero">',
'    <div class="menu-hero-bg"></div>',
'    <div class="menu-hero-content">',
'      <div class="menu-hero-logo"><i class="fas fa-utensils"></i></div>',
'      <h1 id="negocioNombre">Pedido Online</h1>',
'      <p id="negocioSub">Arma tu pedido y lo recibimos enseguida</p>',
'      <div class="origen-badge-hero" id="origenBadge" style="display:none"></div>',
'    </div>',
'  </header>',
'  <nav class="mobile-cat-nav" id="mobileCatNav" aria-label="Categorias">',
'    <div class="mobile-cat-scroll" id="mobileCatScroll"></div>',
'  </nav>',
'  <main class="pedido-layout">',
'    <section class="pedido-carta">',
'      <div class="menu-categories" id="menuCategorias" role="tablist"></div>',
'      <div class="menu-items" id="menuItems" role="tabpanel"></div>',
'    </section>',
'    <aside class="pedido-carrito-sidebar" id="carritoSidebar">',
'      <div class="carrito-header">',
'        <h3><i class="fas fa-shopping-bag"></i> Tu pedido</h3>',
'        <span class="carrito-count" id="carritoCount">0 items</span>',
'      </div>',
'      <div class="carrito-items" id="carritoItems">',
'        <div class="carrito-vacio"><i class="fas fa-shopping-bag"></i><p>Todavia no agregaste nada</p></div>',
'      </div>',
'      <div class="carrito-total-row" id="carritoTotalRow" style="display:none">',
'        <span>Total estimado</span><strong id="carritoTotal">$0</strong>',
'      </div>',
'      <button class="btn btn-primary btn-block" id="btnConfirmar"',
'              onclick="PedidoOnline.abrirFormulario()" style="display:none">',
'        <i class="fas fa-check-circle"></i> Confirmar pedido',
'      </button>',
'    </aside>',
'  </main>',
'  <button class="carrito-flotante" id="carritoFlotante"',
'          onclick="PedidoOnline.toggleCarritoMobile()" style="display:none" aria-label="Ver carrito">',
'    <i class="fas fa-shopping-bag"></i>',
'    <span class="carrito-flotante-count" id="carritoFlotanteCount">0</span>',
'  </button>',
].join('\r\n');

fs.writeFileSync(P, head, 'utf8');
console.log('OK pedido.html parte 1');
